name: fluuter_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  file_picker: ^6.1.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  carousel_slider: ^4.0.0
  flutter:
    sdk: flutter

  get: ^4.6.5
  google_fonts: ^6.1.0
  hexcolor: ^3.0.1
  persistent_bottom_nav_bar: ^5.0.2
  google_maps_flutter: ^2.6.0
  location: ^5.0.3
  provider: ^6.0.5
  image_picker: ^1.0.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
